void call_swift(const char * text);
void call_oc(const char * text);
void call_rust(const char * text);
void call_nim(const char * text);
void call_go(const char * text);
void call_zig(const char * text);
void call_d(const char * text);
void call_cpp(const char * text);
void call_c(const char * text);
